using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace EventApplication.Models
{
    public class SampleData : DropCreateDatabaseAlways<EventDB>
    {
        protected override void Seed(EventDB context)
        {
            var eventTypes = new List<EventType>
            {
                new EventType { Type = "Concert" },
                new EventType { Type = "Carnival" },
                new EventType { Type = "Graduation Party" },
                new EventType { Type = "Formal" },
                new EventType { Type = "Basketball Game" },
                new EventType { Type = "Marathon" },
                new EventType { Type = "Bake Sale" },
                new EventType { Type = "Open Mic Night" },
                new EventType { Type = "Circus Performance" },
                new EventType { Type = "Job Fair" }
            };

            new List<Event>
            {
                new Event { EventType = eventTypes.Single(g => g.Type == "Concert"), EventTitle = "Katy Perry Concert", EventDescription = "A Katy Perry concert in downtown Cleveland.", StartDate = DateTime.Now.AddDays(90), EndDate = DateTime.Now.AddDays(90).AddHours(3), City = "Cleveland", State = "OH", OrganizerName = "Katy Perry", MaxTickets = 300, AvailableTickets = 200},
                new Event { EventType = eventTypes.Single(g => g.Type == "Marathon"), EventTitle = "Fun Run", EventDescription = "Twenty-six miles through the metroparks.", StartDate = DateTime.Now.AddDays(40).AddHours(3), EndDate = DateTime.Now.AddDays(40).AddHours(5), City = "Chicago", State = "IL", OrganizerName = "Ted Marx", MaxTickets = 600, AvailableTickets = 300},
                new Event { EventType = eventTypes.Single(g => g.Type == "Open Mic Night"), EventTitle = "Dave's Bar Comedy Night", EventDescription = "Microphone open for stand-up comedians all night.", StartDate = new DateTime(2019, 5, 30, 18, 0, 0), EndDate = new DateTime(2019, 5, 31, 0, 0, 0), City = "Miami", State = "FL", OrganizerName = "Dave Smith", MaxTickets = 80, AvailableTickets = 50},
                new Event { EventType = eventTypes.Single(g => g.Type == "Carnival"), EventTitle = "Home Days", EventDescription = "Food, games, and rides.", StartDate = DateTime.Now.AddDays(60), EndDate = DateTime.Now.AddDays(60).AddHours(3), City = "Parma", State = "OH", OrganizerName = "Bob Jones", MaxTickets = 300, AvailableTickets = 200},
                new Event { EventType = eventTypes.Single(g => g.Type == "Graduation Party"), EventTitle = "Chloe's Graduation Party", EventDescription = "Class of 2019 welcome.", StartDate = DateTime.Now.AddDays(46).AddHours(1), EndDate = DateTime.Now.AddDays(46).AddHours(5), City = "Pittsburgh", State = "PA", OrganizerName = "Chloe Sanders", MaxTickets = 400, AvailableTickets = 300},
                new Event { EventType = eventTypes.Single(g => g.Type == "Circus Performance"), EventTitle = "Big Apple Circus", EventDescription = "Trapeze, clowns, flame throwers and more.", StartDate = new DateTime(2019, 5, 30, 18, 0, 0), EndDate = new DateTime(2019, 5, 31, 0, 0, 0), City = "New York City", State = "NY", OrganizerName = "Bailey Steward", MaxTickets = 600, AvailableTickets = 4},
                new Event { EventType = eventTypes.Single(g => g.Type == "Job Fair"), EventTitle = "IT Job Fair", EventDescription = "Programming and development jobs in our area.", StartDate = DateTime.Now.AddDays(60), EndDate = DateTime.Now.AddDays(60).AddHours(3), City = "Denver", State = "CO", OrganizerName = "IBM", MaxTickets = 300, AvailableTickets = 200},
                new Event { EventType = eventTypes.Single(g => g.Type == "Basketball Game"), EventTitle = "Fun Run", EventDescription = "Twenty-six miles through the metroparks.", StartDate = DateTime.Now.AddDays(46).AddHours(1), EndDate = DateTime.Now.AddDays(46).AddHours(5), City = "Chicago", State = "IL", OrganizerName = "Ted Marx", MaxTickets = 600, AvailableTickets = 300},
                new Event { EventType = eventTypes.Single(g => g.Type == "Bake Sale"), EventTitle = "Amy's Catering Bake Sale", EventDescription = "Sample Amy's baked goods and consider her for your next event.", StartDate = new DateTime(2019, 5, 30, 18, 0, 0), EndDate = new DateTime(2019, 5, 31, 0, 0, 0), City = "Nashville", State = "TN", OrganizerName = "Amy Childs", MaxTickets = 80, AvailableTickets = 50},
                new Event { EventType = eventTypes.Single(g => g.Type == "Formal"), EventTitle = "King and Queen Ball", EventDescription = "Ballroom dancing.", StartDate = DateTime.Now.AddDays(60), EndDate = DateTime.Now.AddDays(60).AddHours(3), City = "Salt Lake City", State = "UT", OrganizerName = "Elizabeth Bennet", MaxTickets = 300, AvailableTickets = 200},
                new Event { EventType = eventTypes.Single(g => g.Type == "Marathon"), EventTitle = "Pink Run", EventDescription = "Run for breast cancer awareness.", StartDate = DateTime.Now.AddDays(46).AddHours(1), EndDate = DateTime.Now.AddDays(46).AddHours(5), City = "Albuqurque", State = "NM", OrganizerName = "Jimmy Neutron", MaxTickets = 600, AvailableTickets = 300},
                new Event { EventType = eventTypes.Single(g => g.Type == "Open Mic Night"), EventTitle = "Sam's Bar Comedy Night", EventDescription = "Microphone open for stand-up comedians all night.", StartDate = new DateTime(2019, 5, 30, 18, 0, 0), EndDate = new DateTime(2019, 5, 31, 0, 0, 0), City = "Tucson", State = "AZ", OrganizerName = "Samuel Durkin", MaxTickets = 80, AvailableTickets = 50},
                new Event { EventType = eventTypes.Single(g => g.Type == "Concert"), EventTitle = "Julia Michaels Concert", EventDescription = "A Julia Michaels concert at House of Blues.", StartDate = DateTime.Now.AddDays(60), EndDate = DateTime.Now.AddDays(60).AddHours(3), City = "Cleveland", State = "OH", OrganizerName = "Julia Michaels", MaxTickets = 300, AvailableTickets = 200},
                new Event { EventType = eventTypes.Single(g => g.Type == "Carnival"), EventTitle = "Indoor Amusement Park", EventDescription = "Fun for kids of all ages.", StartDate = DateTime.Now.AddDays(46).AddHours(1), EndDate = DateTime.Now.AddDays(46).AddHours(5), City = "Omaha", State = "NE", OrganizerName = "Sugar Ray", MaxTickets = 600, AvailableTickets = 300},
                new Event { EventType = eventTypes.Single(g => g.Type == "Graduation Party"), EventTitle = "Raina's Graduation Party", EventDescription = "College and high school graduation party.", StartDate = new DateTime(2019, 5, 30, 18, 0, 0), EndDate = new DateTime(2019, 5, 31, 0, 0, 0), City = "Columbus", State = "OH", OrganizerName = "Raina May", MaxTickets = 100, AvailableTickets = 50},
                new Event { EventType = eventTypes.Single(g => g.Type == "Circus Performance"), EventTitle = "Barnum Bailey Circus", EventDescription = "In town for one night only.", StartDate = DateTime.Now.AddDays(1), EndDate = DateTime.Now.AddDays(1).AddHours(3), City = "Fort Worth", State = "TX", OrganizerName = "Barnum", MaxTickets = 300, AvailableTickets = 200},
                new Event { EventType = eventTypes.Single(g => g.Type == "Job Fair"), EventTitle = "Local Job Fair", EventDescription = "Job Fair at the highschool.", StartDate = DateTime.Now.AddDays(46).AddHours(1), EndDate = DateTime.Now.AddDays(46).AddHours(5), City = "Chicago", State = "IL", OrganizerName = "John Rango", MaxTickets = 600, AvailableTickets = 300},
                new Event { EventType = eventTypes.Single(g => g.Type == "Basketball Game"), EventTitle = "Cavs Game", EventDescription = "Cleveland Cavs vs. Golden State Warriors.", StartDate = new DateTime(2019, 5, 31, 18, 0, 0), EndDate = new DateTime(2019, 5, 31, 0, 0, 0), City = "Cleveland", State = "OH", OrganizerName = "Fred Roth", MaxTickets = 1000, AvailableTickets = 800},
                new Event { EventType = eventTypes.Single(g => g.Type == "Bake Sale"), EventTitle = "Normandy Bake Sale", EventDescription = "Fundraiser for the band at Normandy.", StartDate = DateTime.Now.AddDays(60), EndDate = DateTime.Now.AddDays(60).AddHours(3), City = "Dallas", State = "TX", OrganizerName = "Sean Greene", MaxTickets = 300, AvailableTickets = 200},
                new Event { EventType = eventTypes.Single(g => g.Type == "Formal"), EventTitle = "Senior Prom", EventDescription = "Hawaiian themed prom night.", StartDate = DateTime.Now.AddDays(1).AddHours(1), EndDate = DateTime.Now.AddDays(1).AddHours(5), City = "Ocean City", State = "MD", OrganizerName = "Ted Marx", MaxTickets = 600, AvailableTickets = 300},
                new Event { EventType = eventTypes.Single(g => g.Type == "Open Mic Night"), EventTitle = "Annual Comedy Night", EventDescription = "Microphone open for stand-up comedians all night.", StartDate = new DateTime(2019, 5, 30, 18, 0, 0), EndDate = new DateTime(2019, 5, 31, 0, 0, 0), City = "Honolulu", State = "HA", OrganizerName = "Desmond Lim", MaxTickets = 80, AvailableTickets = 50},
                new Event { EventType = eventTypes.Single(g => g.Type == "Concert"), EventTitle = "Halsey Concert", EventDescription = "A Halsey concert in downtown Cleveland.", StartDate = DateTime.Now.AddDays(60), EndDate = DateTime.Now.AddDays(60).AddHours(3), City = "Cleveland", State = "OH", OrganizerName = "Halsey", MaxTickets = 300, AvailableTickets = 200},
                new Event { EventType = eventTypes.Single(g => g.Type == "Marathon"), EventTitle = "Race For the Cure", EventDescription = "Raise money for cancer research.", StartDate = DateTime.Now.AddDays(46).AddHours(1), EndDate = DateTime.Now.AddDays(46).AddHours(5), City = "Kansas City", State = "KA", OrganizerName = "San Holo", MaxTickets = 600, AvailableTickets = 300},
                new Event { EventType = eventTypes.Single(g => g.Type == "Carnival"), EventTitle = "Traveling Carnival", EventDescription = "Microphone open for stand-up comedians all night.", StartDate = new DateTime(2019, 5, 30, 18, 0, 0), EndDate = new DateTime(2019, 5, 31, 0, 0, 0), City = "Miami", State = "FL", OrganizerName = "Dave Smith", MaxTickets = 80, AvailableTickets = 50},
                new Event { EventType = eventTypes.Single(g => g.Type == "Bake Sale"), EventTitle = "Pampered Chef Bake Sale", EventDescription = "Sample foods made by our chefs.", StartDate = DateTime.Now.AddDays(1), EndDate = DateTime.Now.AddDays(1).AddHours(3), City = "Atlanta", State = "GE", OrganizerName = "Marvin Gatrix", MaxTickets = 300, AvailableTickets = 200},
                new Event { EventType = eventTypes.Single(g => g.Type == "Basketball Game"), EventTitle = "College Basketball Game", EventDescription = "Tigers vs. Bears.", StartDate = DateTime.Now.AddDays(46).AddHours(1), EndDate = DateTime.Now.AddDays(46).AddHours(5), City = "Detroit", State = "MI", OrganizerName = "Corbin Bleu", MaxTickets = 600, AvailableTickets = 300},
                new Event { EventType = eventTypes.Single(g => g.Type == "Job Fair"), EventTitle = "Baltimore College Job Fair", EventDescription = "Big companies in the area recruiting college graduates.", StartDate = DateTime.Now.AddDays(1).AddHours(8), EndDate = DateTime.Now.AddDays(1).AddHours(11), City = "Baltimore", State = "MD", OrganizerName = "Chloe Raylore", MaxTickets = 80, AvailableTickets = 50},
                new Event { EventType = eventTypes.Single(g => g.Type == "Concert"), EventTitle = "Logic Concert", EventDescription = "Confessions of a Dangerous Mind tour.", StartDate = DateTime.Now.AddDays(60), EndDate = DateTime.Now.AddDays(60).AddHours(3), City = "Seattle", State = "WA", OrganizerName = "Bobby Tarantino", MaxTickets = 1500, AvailableTickets = 200},
                new Event { EventType = eventTypes.Single(g => g.Type == "Marathon"), EventTitle = "Terrain Race", EventDescription = "Obstacle course.", StartDate = DateTime.Now.AddDays(46).AddHours(1), EndDate = DateTime.Now.AddDays(46).AddHours(5), City = "Portland", State = "ME", OrganizerName = "Emily Overholt", MaxTickets = 600, AvailableTickets = 300},
                new Event { EventType = eventTypes.Single(g => g.Type == "Open Mic Night"), EventTitle = "Fat Head's Karaoke Night", EventDescription = "Karaoke and $2 beers.", StartDate = DateTime.Now.AddDays(1), EndDate = DateTime.Now.AddDays(2), City = "Los Angeles", State = "CA", OrganizerName = "Jolene Tarantino", MaxTickets = 80, AvailableTickets = 50},
            }.ForEach(e => context.Events.Add(e));
        }
    }
}